name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pip
  - matplotlib
  - plotly
  - pillow
  - mlflow>=1.21.0
  - wandb
  - pip:
      - omegaconf
      - scikit-learn>=0.24.0
